---
title: "Explore 01"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar: 
      - { icon: "fa-github", href: "https://github.com/libjohn/workshop_dash_explore", align: right }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(crosstalk)
library(plotly)
library(DT)
library(mapview)

sbux_triangle <- read_csv("data/All_Starbucks_Locations_in_the_US_-_Map.csv") %>% filter(City == "Raleigh" | City == "Durham" | City == "Chapel Hill")
sbux_shared_data <- SharedData$new(sbux_triangle)

canes <- read_csv("data/hurricanes.csv")
canes_shared_data <- SharedData$new(canes)

unique(starwars$eye_color)

sw_eye <- starwars %>% 
  filter(eye_color == str_extract(eye_color, "\\w+")) %>% 
  filter(eye_color != "unknown", eye_color != "hazel", eye_color != "white") %>% 
  filter(mass < 200) %>% 
  mutate(eye_color = fct_infreq(eye_color)) %>% 
  mutate(species = fct_rev(fct_infreq(species)))

sw_eye_levels <- levels(sw_eye$eye_color)
  
ggplot(sw_eye, aes(mass, height)) + 
  geom_point(aes(color = eye_color)) + 
  scale_color_manual(values = sw_eye_levels)


sw_eye_ggp2 <- ggplot(sw_eye, aes(mass, height)) + 
  geom_point(aes(color = eye_color)) + 
  scale_color_manual(values = sw_eye_levels)

ggplotly(sw_eye_ggp2)

plot_ly(data = sw_eye, x = ~mass, y = ~height, 
        color = ~eye_color, colors = sw_eye_levels,
        text = ~name, mode = "markers")   %>% 
  layout(title = "StarWars Character EYe Color")

```

Page 1
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Triangle Starbucks Locations 

```{r}
mapview(sbux_triangle, xcol = "Longitude", ycol = "Latitude", crs = 4269, grid = FALSE)

#filter_slider()
```

> Data Scource: Starbucks 2012

Column {data-width=350}
-----------------------------------------------------------------------

### _Star Wars_ Eye Color

```{r}
ggplotly(sw_eye_ggp2)
```

### Chart C

```{r}
plot_ly(data = sw_eye, x = ~mass, y = ~height, 
        color = ~eye_color, colors = sw_eye_levels,
        text = ~name, mode = "markers")   %>% 
  layout(title = "\nStarWars Character Eye Color")
```

### Eye Color of Starwars Characters

```{r}
ggplotly(ggplot(starwars) +
  geom_bar(aes(x = fct_rev(fct_lump(fct_infreq(eye_color), n = 6))), 
           fill = "grey") + 
  coord_flip() +
  geom_bar(data = starwars %>% filter(eye_color == "orange"),
           aes(eye_color), fill = "orange") +
  labs(x = "", y = ""))
```

> This is a ggplot static plot.  Data Source: dplyr::starwars

Page 2 {data-icon="fa-hashtag"}
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r}
shortspecies <- c("Human", "Droid", "Wookiee" )

shared_sw_eye <- SharedData$new(sw_eye)

filter_slider("height", "Height", shared_sw_eye, ~height)
filter_select("hair", "Hair Color", shared_sw_eye, ~hair_color)
filter_select("shortspecies", "Select Species", shared_sw_eye, shortspecies)
filter_checkbox("sw_eye_levels", "Eye Color", shared_sw_eye, ~eye_color)
```



Link to [HOME](#page-1)


Column
-----------------------------------------------------------------------

### Chart 5

```{r}
ggplotly(shared_sw_eye %>% 
  ggplot(aes(eye_color)) +
  geom_bar())
```


Column
-----------------------------------------------------------------------

### chart 6

```{r}
plot_ly(data = shared_sw_eye, x = ~mass, y = ~height, 
        color = ~eye_color, colors = sw_eye_levels,
        text = ~name, mode = "markers")   %>% 
  layout(title = "\nStarWars Character Eye Color", height = 400)


```

###  Some Guages

```{r}
ggplotly(ggplot(shared_sw_eye, aes(x = species)) + geom_bar() + coord_flip())
```

Page 3
=====================

```{r}
sessioninfo::session_info()
```