---
title: "trump approval rating -- time series"
author: "John Little"
date: "`r Sys.Date()`"
abstract: "Put out a timeseries graph via ggplot2plotly"
output: html_notebook
---

```{r}
library(tidyverse)  # dplyr, part of tidyverse,  has spread() & gather() 
library(plotly)
```


## Data from fiveThirtyEight.com

- [approval ratings](https://github.com/fivethirtyeight/data/tree/master/trump-approval-ratings)
- [**topline**](https://projects.fivethirtyeight.com/trump-approval-data/approval_topline.csv)


```{r}
trump <- read_csv("https://projects.fivethirtyeight.com/trump-approval-data/approval_topline.csv", 
                  col_types = cols(modeldate = col_date(format = "%m/%d/%Y"), 
                                   timestamp = col_datetime(format = "%H:%M:%S %d %b %Y ")))
trump
```

## Munge data

```{r}
trump_over_under <- trump %>% 
  filter(subgroup == "All polls") %>% 
  select(modeldate, approve_estimate, disapprove_estimate) %>%
  gather("pol_type", "score", -modeldate)

trump_over_under
```



## ggplot 

```{r}
ts_4_ggpltly <- ggplot(trump_over_under, aes(x = modeldate, y = score, color = pol_type)) +
  geom_line() +
  scale_color_manual(values = c("forestgreen", "firebrick"),
                     labels = c("Approve", "Disapprove")) +
  labs(x = "Date", y = "Approval Rating",
       color = "",
       caption = "Data Source:  fivethirtyeight.com")

ts_4_ggpltly
```

```{r}
ggplotly(ts_4_ggpltly)
```



``` r
# Example from tk_ts documentation
data_tbl <- tibble::tibble(
    date = seq.Date(as.Date("2016-01-01"), by = 1, length.out = 5),
    x    = rep("chr values", 5),
    y    = cumsum(1:5),
    z    = cumsum(11:15) * rnorm(1))

data_tbl

tk_ts(data_tbl, start = 2016)
```



``` r
# Working but the x axis is bonk
ap_4_dy <- allpolls %>% 
  select(modeldate, approve_estimate, disapprove_estimate) %>% 
  tk_ts(start = 20170201) 

ap_4_dy <- allpolls %>% 
  select(modeldate, approve_estimate, disapprove_estimate) %>% 
  #tk_ts()
  tk_ts(start = 2017, freq = 365) 

ap_4_dy

#idx <- tk_index(allpolls)
```


``` r 
This is what was working, even with the bonk x axis
ap_4_dy %>% 
  dygraph() %>% 
  dyRangeSelector(dateWindow = c("2017-02-01", "2018-11-30"))

```



``` r
# from dygraph documentation
class(mdeaths)
head(mdeaths)
lungDeaths <- cbind(mdeaths, fdeaths)
dygraph(lungDeaths)
```


```{r}
sessioninfo::session_info()
```


